import "server-only";

import {
  mkdir,
  readdir,
  readFile,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";

import path from "node:path";

import {
  ffmpeg,
  FfmpegError,
  probe,
  validateProbed,
  type ProbedMedia,
} from "./ffmpeg";

import { storagePaths } from "@/lib/media/paths";

/**
 * VideoProcessingService
 *
 * IMPORTANT:
 *
 * The original uploaded source is NEVER modified.
 *
 * FFmpeg works only on a temporary local copy.
 *
 * Processing behavior:
 *
 * - All supported video formats are processed into a
 *   browser-compatible HLS playback version.
 *
 * - The original uploaded file remains untouched in storage.
 *
 * - HLS is used as the single playback format so MP4, TS,
 *   MOV, WEBM, MKV and M4V all follow the same playback path.
 *
 * HLS output:
 *
 *   original/
 *     playlist.m3u8
 *     segment-0000.ts
 *     segment-0001.ts
 *     ...
 *
 * Everything generated by FFmpeg is written to the worker
 * temporary directory first.
 */

export type RenditionResult = {
  label: string;
  width: number;
  height: number;
  bitrateKbps: number;

  /** Local directory containing playlist.m3u8 + segments. */
  localDir: string;

  /** Storage key for the rendition playlist. */
  playlistKey: string;

  sizeBytes: number;
};

export type ProcessingOutput = {
  media: ProbedMedia;

  thumbnailPath: string;

  /**
   * Hover preview.
   *
   * Currently disabled from the main pipeline because
   * the worker does not require it for playback.
   */
  previewPath: string | null;

  /**
   * Local HLS master playlist.
   *
   * All supported video inputs produce this playlist.
   */
  masterPlaylistPath: string | null;

  /**
   * Browser-compatible HLS renditions.
   */
  renditions: RenditionResult[];
};

const SEGMENT_SECONDS = 6;

/**
 * HLS can be generated much faster by remuxing when the
 * source already contains browser-friendly H.264/AAC.
 *
 * This is especially useful for:
 *
 * - .ts
 * - .mkv
 * - .mov
 * - .m4v
 *
 * because we do not need to decode and re-encode the
 * video when the codecs are already suitable.
 */
function canRemuxToHls(
  media: ProbedMedia,
): boolean {
  return (
    media.videoCodec === "h264" &&
    (
      !media.hasAudio ||
      media.audioCodec === "aac"
    )
  );
}

/**
 * Picks a useful frame for thumbnail/preview.
 */
export function thumbnailTimestamp(
  durationSeconds: number,
): number {
  /*
   * Extremely short video.
   */
  if (
    durationSeconds <= 1
  ) {
    return Math.max(
      0,
      durationSeconds / 2,
    );
  }

  /*
   * Short video.
   */
  if (
    durationSeconds <= 4
  ) {
    return Math.min(
      durationSeconds * 0.75,
      Math.max(
        0.5,
        durationSeconds / 2,
      ),
    );
  }

  /*
   * Normal video.
   */
  return Math.min(
    60,
    Math.max(
      2.5,
      durationSeconds * 0.1,
    ),
  );
}

/**
 * Generate a reliable still thumbnail.
 *
 * Multiple timestamps are attempted because some
 * webcam videos begin with a short black/loading section.
 */
export async function generateThumbnail(
  sourcePath: string,
  workDir: string,
  durationSeconds: number,
): Promise<string> {
  const output =
    path.join(
      workDir,
      "thumbnail.webp",
    );

  const candidates =
    Array.from(
      new Set(
        [
          thumbnailTimestamp(
            durationSeconds,
          ),

          1.5,
          2.5,
          5,

          durationSeconds * 0.25,
          durationSeconds * 0.5,
          durationSeconds * 0.75,
        ]
          .filter(
            (value) =>
              Number.isFinite(value) &&
              value >= 0 &&
              value < durationSeconds,
          )
          .map(
            (value) =>
              Math.max(
                0,
                Math.min(
                  value,
                  Math.max(
                    0,
                    durationSeconds - 0.1,
                  ),
                ),
              ),
          ),
      ),
    );

  let lastError:
    unknown = null;

  for (
    const at of candidates
  ) {
    try {
      await rm(
        output,
        {
          force: true,
        },
      ).catch(
        () => undefined,
      );

      await ffmpeg([
        "-y",

        "-i",
        sourcePath,

        "-ss",
        at.toFixed(2),

        "-frames:v",
        "1",

        "-vf",
        "scale='min(1280,iw)':-2:flags=lanczos",

        "-c:v",
        "libwebp",

        "-quality",
        "82",

        "-compression_level",
        "6",

        output,
      ]);

      const generated =
        await stat(
          output,
        ).catch(
          () => null,
        );

      if (
        generated &&
        generated.size > 0
      ) {
        console.info(
          `[processor] thumbnail generated at ${at.toFixed(2)}s`,
        );

        return output;
      }
    } catch (error) {
      lastError = error;

      console.warn(
        `[processor] thumbnail attempt failed at ${at.toFixed(2)}s`,
      );
    }
  }

  throw new FfmpegError(
    "Unable to generate a video thumbnail.",
    lastError instanceof Error
      ? lastError.message
      : "No usable video frame was found.",
  );
}

/**
 * Generate an animated WebP hover preview.
 *
 * This function remains available for future use,
 * but it is intentionally not called by processVideo()
 * because playback does not depend on it.
 */
export async function generatePreview(
  sourcePath: string,
  workDir: string,
  durationSeconds: number,
): Promise<string | null> {
  const output =
    path.join(
      workDir,
      "preview.webp",
    );

  const at =
    thumbnailTimestamp(
      durationSeconds,
    );

  const previewDuration =
    Math.min(
      3,
      Math.max(
        0.5,
        durationSeconds - at,
      ),
    );

  try {
    await ffmpeg([
      "-y",

      "-ss",
      at.toFixed(2),

      "-t",
      previewDuration.toFixed(2),

      "-i",
      sourcePath,

      "-vf",
      "fps=10,scale=480:-2:flags=lanczos",

      "-c:v",
      "libwebp",

      "-loop",
      "0",

      "-quality",
      "60",

      output,
    ]);

    const generated =
      await stat(
        output,
      ).catch(
        () => null,
      );

    if (
      !generated ||
      generated.size <= 0
    ) {
      return null;
    }

    return output;
  } catch (error) {
    console.warn(
      `[processor] hover preview generation failed: ${
        error instanceof Error
          ? error.message
          : "unknown error"
      }`,
    );

    return null;
  }
}

/**
 * Generate one browser-compatible HLS rendition.
 *
 * The original source file is only read.
 *
 * When the source already uses H.264/AAC, FFmpeg tries
 * to remux it without re-encoding. This is significantly
 * faster for TS/H264 sources.
 *
 * When the codec is not suitable for browser playback,
 * FFmpeg creates H.264/AAC HLS output.
 */
export async function generateRendition(
  sourcePath: string,
  workDir: string,
  videoId: string,
  source: ProbedMedia,
): Promise<RenditionResult> {
  const label = "original";

  const localDir =
    path.join(
      workDir,
      label,
    );

  await mkdir(
    localDir,
    {
      recursive: true,
    },
  );

  const outputWidth =
    Math.max(
      2,
      Math.floor(
        source.width / 2,
      ) * 2,
    );

  const outputHeight =
    Math.max(
      2,
      Math.floor(
        source.height / 2,
      ) * 2,
    );

  const playlistPath =
    path.join(
      localDir,
      "playlist.m3u8",
    );

  const segmentPattern =
    path.join(
      localDir,
      "segment-%04d.ts",
    );

  const args: string[] = [
    "-y",

    "-i",
    sourcePath,

    "-map",
    "0:v:0",
  ];

  if (
    source.hasAudio
  ) {
    args.push(
      "-map",
      "0:a:0?",
    );
  }

  const remux =
    canRemuxToHls(
      source,
    );

  if (remux) {
    /*
     * Fast path:
     *
     * Source is already H.264/AAC.
     *
     * Do NOT decode/re-encode the video.
     */
    args.push(
      "-fflags",
      "+genpts",

      "-avoid_negative_ts",
      "make_zero",

      "-c:v",
      "copy",
    );

    if (
      source.hasAudio
    ) {
      args.push(
        "-c:a",
        "copy",
      );
    } else {
      args.push(
        "-an",
      );
    }
  } else {
    /*
     * Full compatibility path:
     *
     * H.264 video
     * AAC audio
     * yuv420p
     */
    args.push(
      "-vf",
      `scale=${outputWidth}:${outputHeight}:flags=lanczos`,

      "-c:v",
      "libx264",

      "-preset",
      "veryfast",

      "-crf",
      "23",

      "-pix_fmt",
      "yuv420p",

      "-force_key_frames",
      `expr:gte(t,n_forced*${SEGMENT_SECONDS})`,

      "-sc_threshold",
      "0",
    );

    if (
      source.hasAudio
    ) {
      args.push(
        "-c:a",
        "aac",

        "-b:a",
        "128k",

        "-ar",
        "48000",
      );
    } else {
      args.push(
        "-an",
      );
    }
  }

  /*
   * HLS output.
   */
  args.push(
    "-f",
    "hls",

    "-hls_time",
    String(
      SEGMENT_SECONDS,
    ),

    "-hls_playlist_type",
    "vod",

    "-hls_segment_filename",
    segmentPattern,

    playlistPath,
  );

  /*
   * Only advertise independent segments when we control
   * the GOP/keyframe structure through transcoding.
   *
   * For remuxed H.264 sources, the original keyframe
   * structure is preserved.
   */
  if (
    !remux
  ) {
    const playlistIndex =
      args.indexOf(
        "-f",
      );

    if (
      playlistIndex >= 0
    ) {
      args.splice(
        playlistIndex + 6,
        0,
        "-hls_flags",
        "independent_segments",
      );
    }
  }

  console.info(
    `[processor] HLS ${remux ? "remux" : "transcode"} started content=${videoId} source=${path.basename(sourcePath)}`,
  );

  await ffmpeg(
    args,
  );

  /*
   * Verify playlist exists.
   */
  const playlistStat =
    await stat(
      playlistPath,
    ).catch(
      () => null,
    );

  if (
    !playlistStat ||
    playlistStat.size <= 0
  ) {
    throw new FfmpegError(
      "FFmpeg did not create a valid HLS playlist.",
      playlistPath,
    );
  }

  /*
   * Calculate generated HLS size.
   */
  const files =
    await readdir(
      localDir,
    );

  let sizeBytes =
    0;

  for (
    const file of files
  ) {
    const filePath =
      path.join(
        localDir,
        file,
      );

    const fileStat =
      await stat(
        filePath,
      ).catch(
        () => null,
      );

    if (
      fileStat?.isFile()
    ) {
      sizeBytes +=
        fileStat.size;
    }
  }

  const bitrateKbps =
    Math.max(
      256,
      Math.round(
        (
          source.bitrate ??
          1_000_000
        ) / 1000,
      ),
    );

  return {
    label,

    width:
      outputWidth,

    height:
      outputHeight,

    bitrateKbps,

    localDir,

    playlistKey:
      storagePaths.hlsVariantPlaylist(
        videoId,
        label,
      ),

    sizeBytes,
  };
}

/**
 * Write the HLS master playlist.
 */
export async function writeMasterPlaylist(
  workDir: string,
  renditions: RenditionResult[],
): Promise<string> {
  if (
    renditions.length === 0
  ) {
    throw new FfmpegError(
      "Cannot create an HLS master playlist without renditions.",
      "No HLS renditions were generated.",
    );
  }

  const lines = [
    "#EXTM3U",
    "#EXT-X-VERSION:3",
  ];

  const ordered =
    [...renditions].sort(
      (a, b) =>
        a.height - b.height,
    );

  for (
    const rendition of ordered
  ) {
    const bandwidth =
      Math.max(
        1,
        rendition.bitrateKbps *
          1000,
      );

    lines.push(
      `#EXT-X-STREAM-INF:BANDWIDTH=${bandwidth},RESOLUTION=${rendition.width}x${rendition.height},NAME="${rendition.label}"`,

      `${rendition.label}/playlist.m3u8`,
    );
  }

  const output =
    path.join(
      workDir,
      "master.m3u8",
    );

  await writeFile(
    output,
    `${lines.join("\n")}\n`,
    "utf8",
  );

  return output;
}

/**
 * Full processing pipeline.
 *
 * Original source is NEVER replaced.
 *
 * ALL supported formats:
 *
 *   - probe
 *   - validate
 *   - thumbnail
 *   - HLS remux when codecs are already H.264/AAC
 *   - HLS transcode when codec conversion is required
 *
 * This makes HLS the single playback path for every
 * supported upload format.
 */
export async function processVideo(
  sourcePath: string,
  workDir: string,
  videoId: string,
): Promise<ProcessingOutput> {
  await mkdir(
    workDir,
    {
      recursive: true,
    },
  );

  /*
   * -------------------------------------------------
   * 1. PROBE ORIGINAL SOURCE
   * -------------------------------------------------
   *
   * FFprobe inspects the actual media container,
   * video codec, audio codec, dimensions and duration.
   *
   * The filename extension is not trusted as the
   * source of truth.
   */
  const media =
    await probe(
      sourcePath,
    );

  /*
   * -------------------------------------------------
   * 2. VALIDATE ACTUAL MEDIA
   * -------------------------------------------------
   */
  const validation =
    validateProbed(
      media,
    );

  if (
    !validation.ok
  ) {
    throw new FfmpegError(
      validation.reason,
      validation.reason,
    );
  }

  /*
   * -------------------------------------------------
   * 3. GENERATE THUMBNAIL
   * -------------------------------------------------
   *
   * Thumbnail generation works from the temporary
   * local copy only.
   */
  const thumbnailPath =
    await generateThumbnail(
      sourcePath,
      workDir,
      media.durationSeconds,
    );

  /*
   * -------------------------------------------------
   * 4. GENERATE BROWSER-COMPATIBLE HLS
   * -------------------------------------------------
   *
   * Every supported input format goes through HLS.
   *
   * When the source already has H.264 video and AAC
   * audio, generateRendition() uses the fast remux
   * path where possible.
   *
   * Otherwise it transcodes to H.264/AAC/yuv420p.
   *
   * The uploaded original file is never modified.
   */
  const rendition =
    await generateRendition(
      sourcePath,
      workDir,
      videoId,
      media,
    );

  const renditions:
    RenditionResult[] = [
      rendition,
    ];

  /*
   * -------------------------------------------------
   * 5. WRITE HLS MASTER PLAYLIST
   * -------------------------------------------------
   *
   * Creates:
   *
   * workDir/master.m3u8
   *
   * The master playlist references:
   *
   * original/playlist.m3u8
   */
  const masterPlaylistPath =
    await writeMasterPlaylist(
      workDir,
      renditions,
    );

  /*
   * -------------------------------------------------
   * 6. VERIFY MASTER PLAYLIST
   * -------------------------------------------------
   */
  const masterStat =
    await stat(
      masterPlaylistPath,
    ).catch(
      () => null,
    );

  if (
    !masterStat ||
    masterStat.size <= 0
  ) {
    throw new FfmpegError(
      "HLS master playlist was not created.",
      masterPlaylistPath,
    );
  }

  console.info(
    `[processor] processing complete video=${videoId} hls=true original-preserved=true source=${path.basename(sourcePath)}`,
  );

  /*
   * -------------------------------------------------
   * 7. RETURN COMPLETE PROCESSING OUTPUT
   * -------------------------------------------------
   */
  return {
    media,

    thumbnailPath,

    previewPath:
      null,

    masterPlaylistPath,

    renditions,
  };
}

/**
 * Best-effort scratch cleanup.
 *
 * Only worker temporary files are deleted.
 *
 * Uploaded original files and generated storage
 * objects are not touched here.
 */
export async function cleanupWorkDir(
  workDir: string,
): Promise<void> {
  await rm(
    workDir,
    {
      recursive: true,
      force: true,
    },
  ).catch(
    () => undefined,
  );
}

/**
 * Read a file when it exists.
 */
export async function readIfExists(
  filePath: string,
): Promise<Buffer | null> {
  try {
    return await readFile(
      filePath,
    );
  } catch {
    return null;
  }
}