import type { NextRequest } from "next/server";
import { z } from "zod";
import { requireApiRole } from "@/lib/auth/guards";
import { handleRouteError, ok, rateLimitedResponse } from "@/lib/api/response";
import { ApiError } from "@/lib/api/errors";
import { clientIdentifier, rateLimit } from "@/lib/security/rate-limit";
import { recordUploadedAsset } from "@/server/services/media-service";
import { resolveAssetUrl } from "@/lib/media";
import { db } from "@/lib/db";

export const runtime = "nodejs";

/**
 * Step 2 of a direct upload: record what landed.
 *
 * The service verifies the object exists in storage and reads its real size
 * before writing a row, so a client that skipped the upload cannot register a
 * phantom asset, and a claimed size is never taken at face value.
 */
const bodySchema = z.object({
  objectKey: z.string().min(3).max(400),
  kind: z.enum(["IMAGE", "VIDEO", "AUDIO", "DOCUMENT"]),
  mimeType: z.string().min(3).max(120),
  originalName: z.string().min(1).max(200),
  // Accepted but NOT trusted — see below.
  width: z.coerce.number().int().positive().max(20000).optional(),
  height: z.coerce.number().int().positive().max(20000).optional(),
});

export async function POST(request: NextRequest) {
  try {
    const admin = await requireApiRole("ADMIN", "MODERATOR");

    const limit = await rateLimit("upload", clientIdentifier(request.headers));
    if (!limit.allowed) return rateLimitedResponse(limit.resetAt);

    const body = bodySchema.parse(await request.json());

    // Keys are generated by this server; anything outside the known prefixes
    // did not come from an authorization we issued.
    const allowedPrefix = /^(content|creator|site)\//.test(body.objectKey);
    if (!allowedPrefix || body.objectKey.includes("..")) {
      throw new ApiError("BAD_REQUEST", "That storage key is not recognised.");
    }

    /*
      Client-reported dimensions are discarded. After a direct upload the
      server has not seen the bytes, so the honest options are to read the
      header back from storage or to store nothing. Storing nothing is chosen
      here: a dimension is only a layout hint, and a HEAD-plus-ranged-GET per
      upload is not worth it. The proxy-upload path, which does see the bytes,
      records real dimensions.
    */
    const asset = await recordUploadedAsset({
      objectKey: body.objectKey,
      kind: body.kind,
      mimeType: body.mimeType,
      originalName: body.originalName,
      uploadedById: admin.id,
      width: null,
      height: null,
    });

    if (!asset) {
      throw new ApiError(
        "BAD_REQUEST",
        "No uploaded file was found at that location. The upload may not have completed.",
      );
    }

    const record = await db.mediaAsset.findUnique({ where: { id: asset.id } });
    const url = await resolveAssetUrl(record);

    console.info(`[media] upload recorded asset=${asset.id} bytes=${asset.sizeBytes}`);

    return ok({ assetId: asset.id, url, sizeBytes: asset.sizeBytes }, { status: 201 });
  } catch (error) {
    return handleRouteError(error);
  }
}
