/**
 * Object key layout for the media pipeline.
 *
 * Keys are derived from application-controlled identifiers.
 * The original uploaded filename is never used as a storage path.
 *
 * Storage layout:
 *
 * videos/original/
 *   Private untouched uploads.
 *
 * videos/hls/
 *   Generated HLS playlists and MPEG-TS segments.
 *
 * videos/thumbnails/
 *   Generated still thumbnails.
 *
 * videos/previews/
 *   Generated animated previews.
 */

/**
 * Extensions allowed by the storage path layer.
 *
 * Video source files:
 * - mp4
 * - ts
 * - mov
 * - webm
 * - mkv
 * - m4v
 *
 * Image assets:
 * - webp
 * - jpg
 * - jpeg
 * - png
 */
const ALLOWED_STORAGE_EXTENSIONS =
  new Set([
    "mp4",
    "ts",
    "mov",
    "webm",
    "mkv",
    "m4v",
    "webp",
    "jpg",
    "jpeg",
    "png",
  ]);

/**
 * Guards against malformed identifiers ever reaching a storage key.
 *
 * IDs and generated labels may contain:
 * - letters
 * - numbers
 * - underscore
 * - hyphen
 *
 * Path separators and other characters are rejected rather than silently
 * removed. This prevents an invalid identifier from becoming a different
 * valid identifier accidentally.
 */
function safeSegment(
  value: string,
): string {
  const cleaned =
    value.trim();

  if (
    !cleaned ||
    cleaned.length > 64
  ) {
    throw new Error(
      "Refusing to build a storage key from an unsafe identifier",
    );
  }

  if (
    !/^[a-zA-Z0-9_-]+$/.test(
      cleaned,
    )
  ) {
    throw new Error(
      "Refusing to build a storage key from an unsafe identifier",
    );
  }

  return cleaned;
}

/**
 * Normalize a storage extension.
 *
 * Examples:
 *
 * "mp4"  -> ".mp4"
 * ".mp4" -> ".mp4"
 * "TS"   -> ".ts"
 * ".TS"  -> ".ts"
 *
 * Path separators, multiple extensions and unknown extensions are rejected.
 */
export function normalizeExtension(
  raw: string,
): string {
  const value =
    raw
      .trim()
      .toLowerCase();

  if (!value) {
    throw new Error(
      "A file extension is required",
    );
  }

  /*
   * Never allow paths inside the extension.
   */
  if (
    value.includes("/") ||
    value.includes("\\")
  ) {
    throw new Error(
      "Unsafe file extension",
    );
  }

  /*
   * Accept exactly one optional leading dot.
   */
  const extension =
    value.startsWith(".")
      ? value.slice(1)
      : value;

  /*
   * Extensions must be simple alphanumeric values.
   */
  if (
    !/^[a-z0-9]+$/.test(
      extension,
    )
  ) {
    throw new Error(
      "Unsafe file extension",
    );
  }

  /*
   * Only known storage extensions are allowed.
   */
  if (
    !ALLOWED_STORAGE_EXTENSIONS.has(
      extension,
    )
  ) {
    throw new Error(
      `Unsupported storage extension: .${extension}`,
    );
  }

  return `.${extension}`;
}

/**
 * Object key layout.
 */
export const storagePaths = {
  /**
   * Private untouched source upload.
   *
   * Examples:
   *
   * videos/original/cmt123/source.mp4
   * videos/original/cmt123/source.ts
   */
  source: (
    videoId: string,
    extension: string,
  ) =>
    `videos/original/${safeSegment(
      videoId,
    )}/source${normalizeExtension(
      extension,
    )}`,

  /**
   * HLS master playlist.
   */
  hlsMaster: (
    videoId: string,
  ) =>
    `videos/hls/${safeSegment(
      videoId,
    )}/master.m3u8`,

  /**
   * HLS rendition directory.
   */
  hlsVariantDir: (
    videoId: string,
    label: string,
  ) =>
    `videos/hls/${safeSegment(
      videoId,
    )}/${safeSegment(
      label,
    )}`,

  /**
   * HLS rendition playlist.
   */
  hlsVariantPlaylist: (
    videoId: string,
    label: string,
  ) =>
    `videos/hls/${safeSegment(
      videoId,
    )}/${safeSegment(
      label,
    )}/playlist.m3u8`,

  /**
   * Generated thumbnail.
   */
  thumbnail: (
    videoId: string,
    extension = "webp",
  ) =>
    `videos/thumbnails/${safeSegment(
      videoId,
    )}/thumbnail${normalizeExtension(
      extension,
    )}`,

  /**
   * Generated animated hover preview.
   */
  preview: (
    videoId: string,
  ) =>
    `videos/previews/${safeSegment(
      videoId,
    )}/preview.webp`,

  /**
   * Per-content thumbnail.
   *
   * Token is generated by the application and is therefore also passed
   * through safeSegment().
   */
  contentThumbnail: (
    contentId: string,
    token: string,
    extension: string,
  ) =>
    `content/${safeSegment(
      contentId,
    )}/thumbnail/${safeSegment(
      token,
    )}${normalizeExtension(
      extension,
    )}`,

  /**
   * Private per-content video asset.
   */
  contentVideo: (
    contentId: string,
    token: string,
    extension: string,
  ) =>
    `content/${safeSegment(
      contentId,
    )}/video/${safeSegment(
      token,
    )}${normalizeExtension(
      extension,
    )}`,

  /**
   * Creator avatar.
   */
  creatorAvatar: (
    creatorId: string,
    token: string,
    extension: string,
  ) =>
    `creator/${safeSegment(
      creatorId,
    )}/avatar/${safeSegment(
      token,
    )}${normalizeExtension(
      extension,
    )}`,

  /**
   * Creator banner.
   */
  creatorBanner: (
    creatorId: string,
    token: string,
    extension: string,
  ) =>
    `creator/${safeSegment(
      creatorId,
    )}/banner/${safeSegment(
      token,
    )}${normalizeExtension(
      extension,
    )}`,

  /**
   * Site-level assets.
   *
   * Examples:
   * - logo
   * - favicon
   * - social image
   */
  site: (
    kind: string,
    token: string,
    extension: string,
  ) =>
    `site/${safeSegment(
      kind,
    )}/${safeSegment(
      token,
    )}${normalizeExtension(
      extension,
    )}`,

  /**
   * Everything belonging to one recording.
   *
   * Used when deleting a complete recording and its generated assets.
   */
  prefixes: (
    videoId: string,
  ) => {
    const id =
      safeSegment(
        videoId,
      );

    return [
      `videos/original/${id}/`,
      `videos/hls/${id}/`,
      `videos/thumbnails/${id}/`,
      `videos/previews/${id}/`,
    ];
  },
} as const;

/**
 * True when a storage key contains a derived/presentational asset
 * that may be exposed through the public media layer.
 *
 * Original source videos remain private.
 */
export function isPublicKey(
  key: string,
): boolean {
  /*
   * Normalize separators so Windows-style paths cannot bypass
   * the prefix checks.
   */
  const normalized =
    key
      .replace(
        /\\/g,
        "/",
      )
      .replace(
        /^\/+/,
        "",
      );

  /*
   * Reject traversal-like keys.
   */
  const segments =
    normalized.split("/");

  if (
    segments.includes("..") ||
    segments.includes(".") ||
    normalized.includes("\0")
  ) {
    return false;
  }

  /*
   * Untouched original uploads are private.
   */
  if (
    normalized.startsWith(
      "videos/original/",
    )
  ) {
    return false;
  }

  /*
   * Per-content original videos are private.
   */
  if (
    normalized.startsWith(
      "content/",
    ) &&
    normalized.includes(
      "/video/",
    )
  ) {
    return false;
  }

  /*
   * Derived media is public.
   */
  return (
    normalized.startsWith(
      "videos/hls/",
    ) ||
    normalized.startsWith(
      "videos/thumbnails/",
    ) ||
    normalized.startsWith(
      "videos/previews/",
    ) ||
    normalized.startsWith(
      "content/",
    ) ||
    normalized.startsWith(
      "creator/",
    ) ||
    normalized.startsWith(
      "site/",
    )
  );
}